# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=20)),
                ('PW', models.CharField(max_length=20)),
            ],
        ),
    ]
